"""Download Google Fonts woff2 files referenced in a Google Fonts CSS payload
and emit a self-contained CSS that points at local paths.

Run from the repo root:
    python scripts/vendor_fonts.py

Produces:
    src/magsearch/web/static/fonts/<name>-<style>-<subset>.woff2
    src/magsearch/web/static/fonts.css

The Google Fonts CSS we vendor is fetched with a modern UA so the API returns
variable-axis woff2 URLs (the default UA still gets static TTF).
"""

from __future__ import annotations

import hashlib
import re
import sys
import urllib.request
from pathlib import Path

GFONTS_CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Fraunces:ital,opsz,wght,SOFT,WONK@"
    "0,9..144,300..900,30..100,0..1;"
    "1,9..144,300..900,30..100,0..1"
    "&family=Newsreader:ital,opsz,wght@"
    "0,6..72,300..700;1,6..72,300..700"
    "&display=swap"
)

# Modern UA so the API returns woff2 (variable) URLs instead of static TTFs.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120 Safari/537.36"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
STATIC_DIR = REPO_ROOT / "src" / "magsearch" / "web" / "static"
FONTS_DIR = STATIC_DIR / "fonts"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(GFONTS_CSS_URL).decode("utf-8")

    # Each @font-face block is preceded by a /* subset */ comment; we use that
    # name plus a hash of the URL to produce stable, descriptive filenames.
    pattern = re.compile(
        r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*"
        r"@font-face\s*\{(?P<body>[^}]+)\}",
        re.DOTALL,
    )
    family_re = re.compile(r"font-family:\s*'([^']+)'")
    style_re = re.compile(r"font-style:\s*(\w+)")
    url_re = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")

    out_blocks: list[str] = []
    seen: dict[str, str] = {}
    for m in pattern.finditer(css):
        subset = m.group("subset")
        body = m.group("body")
        family = family_re.search(body).group(1).lower()
        style = style_re.search(body).group(1)
        url = url_re.search(body).group(1)

        digest = hashlib.sha1(url.encode()).hexdigest()[:8]
        fname = f"{family}-{style}-{subset}-{digest}.woff2"
        target = FONTS_DIR / fname

        if url not in seen:
            print(f"  fetching {family} {style} ({subset})…", file=sys.stderr)
            target.write_bytes(fetch(url))
            seen[url] = fname

        rewritten_body = url_re.sub(f"url(fonts/{fname}) format('woff2')", body)
        # Strip the now-redundant trailing `format('woff2')` from the original
        # (the substitution above already injected one).
        rewritten_body = re.sub(
            r"format\('woff2'\)\s*format\('woff2'\)",
            "format('woff2')",
            rewritten_body,
        )
        out_blocks.append(
            f"/* {family} {style} — {subset} */\n"
            f"@font-face {{{rewritten_body.rstrip()}\n}}"
        )

    header = (
        "/* Generated by scripts/vendor_fonts.py from Google Fonts.\n"
        " * Fonts are SIL Open Font License 1.1.\n"
        " * Do not edit by hand — re-run the script to refresh. */\n\n"
    )
    (STATIC_DIR / "fonts.css").write_text(header + "\n\n".join(out_blocks) + "\n")
    print(
        f"wrote {len(seen)} font files and fonts.css "
        f"({len(out_blocks)} @font-face blocks)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
